# Generated by Django 5.2.6 on 2025-12-05 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('status', models.CharField(default='available', max_length=50)),
                ('color', models.TextField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'instrument',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_date', models.CharField(max_length=50)),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.CharField(blank=True, max_length=50, null=True)),
                ('customer', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.customer')),
            ],
            options={
                'db_table': 'rental',
            },
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instrument', models.ForeignKey(db_column='instrument_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.instrument')),
                ('rental', models.ForeignKey(db_column='rental_id', on_delete=django.db.models.deletion.CASCADE, to='rentals.rental')),
            ],
            options={
                'db_table': 'rentalitem',
            },
        ),
    ]
